### ISSUE TITLE
Safari Issues

### ISSUE THREAD

**Issue by GetContented** [etaque/elm-routing-example#1]
Checked this out as an alternative to the complexity of learning how the internals of bogdanp/elmroute works, for learning how to implement SPA routing using the location hash. Spent an hour or two trying to get it working with location.hash only to realise Safari doesn't seem to recognise or trigger the `Transit`  stuff - works fine in Chrome. (Not really sure what's going on here actually). Could you possibly adjust so it also works in Safari? That is, the `SetRoute` message is never received - possibly because the `Transit.tick` is never "done"?

Here are my modifications to get it using the location hash:

```
      <script type="text/javascript">
        var app = Elm.Main.fullscreen(document.location.hash);

        app.ports.setPath.subscribe(function(hash) {
          var loc = document.location.pathname;
          if (loc == undefined || loc == "/") {
            loc = ""
          }
          console.log("CurrentPath + hash: " + loc + hash);
          history.pushState({}, "", loc + hash);
          app.ports.pathUpdates.send(loc + hash);
        });

        window.onpopstate = function(event) {
          console.log("popstate");
          app.ports.pathUpdates.send(document.location.hash);
        };
      </script>
```

**Comment by etaque** [comment]
Sorry, missed notification for your issue. Might be related to this issue in elm-transit:
https://github.com/etaque/elm-transit/pull/2.

I just pushed an upgrade with the fix, could you test it again? I don't have a mac at hand right now.

**Comment by GetContented** [comment]
@etaque thanks, that fixed it! :)
